### PR TITLE
BACKLOG-20309: Truncate path in the middle when too long

### PR DESCRIPTION
**Pull request by cedmail**
## JIRA

https://jira.jahia.org/browse/BACKLOG-20309

## Description

Use overflow/text clipping to keep action button on top
Listen to view port resizing to estimate the size of the path to keep at both end of the string

### CODE REVIEW

**Comment by tdraier** [comment]
The solution looks very complex for just a styling issue ? Note that we have the exact the same issue in jcontent, it would be interesting to also fix it there.
From what I have seen, simply adding  `text-overflow: ellipsis; overflow: hidden` on the typography seems enough . Eventually we can also add `min-width: 0;` , but that does not seem necessary.
Also, I've seen that the dom structure is invalid - we have a div inside a span, and actually 2 nested Typography elements - the outer one coming from TableBodyCell, from moonstone, might not be easy to remove ( @ffffffelix ? ) (this has no impact on the overflow)

**Comment by cedmail** [comment]
> The solution looks very complex for just a styling issue ? Note that we have the exact the same issue in jcontent, it would be interesting to also fix it there. From what I have seen, simply adding `text-overflow: ellipsis; overflow: hidden` on the typography seems enough . Eventually we can also add `min-width: 0;` , but that does not seem necessary. Also, I've seen that the dom structure is invalid - we have a div inside a span, and actually 2 nested Typography elements - the outer one coming from TableBodyCell, from moonstone, might not be easy to remove ( @ffffffelix ? ) (this has no impact on the overflow)

I agree that ellipsis could be enough but it is cutting most of the interesting information. another easier solution would be to cut part of the path at the beginning but same issue you might not notice it is in another site

**Comment by tdraier** [comment]
Maybe we can add a tooltip with the full value ? Cutting part at the beginning can be done by using ltr direction , but I don't know if some part is really more interesting than another
Btw just noticed I pushed the test I did on ellipsis here : https://github.com/Jahia/content-editor/pull/1414

**Comment by cedmail** [comment]
Sounds good, merge your PR I will add the title on the Typography

**Pull request closed without merging**
